jobs:
  example-job:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Таймаут в 10 минут для этой задачи
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "This is a test"
